swagger: "2.0"
info:
  version: "0.0.1"
  title: Sensity Interface Service
# during dev, should point to your local machine
host: 0.0.0.0:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  # Get, Update, Delete  a specific policy category
  /customers/{orgid}/sites/{siteid}/tags/{tagid}:
    x-swagger-router-controller: policy_tag
    # Get a policy tag
    get:
      description: Get a specific policy tag in a site
      operationId: getTag
      parameters:
        - name: orgid
          in: path
          description: The org ID
          required: true
          type: string
        - name: siteid
          in: path
          description: The site ID
          required: true
          type: string
        - name: tagid
          in: path
          description: The policy tag ID
          required: true
          type: string        
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GetTagResponse"
        "404":
          description: Policy Tag Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

    # Delete a policy tag
    delete:
      description: Delete a policy tag in a site
      operationId: deleteTag
      parameters:
        - name: orgid
          in: path
          description: The customer ID
          required: true
          type: string
        - name: siteid
          in: path
          description: The site ID
          required: true
          type: string
        - name: tagid
          in: path
          description: The policy tag ID
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DeleteTagResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    
    # Update a policy tag
    post:
      description: Update a policy tag
      operationId: updateTag
      parameters:
        - name: orgid
          in: path
          description: The customer ID
          required: true
          type: string
        - name: siteid
          in: path
          description: The site ID
          required: true
          type: string
        - name: tagid
          in: path
          description: The policy tag ID
          required: true
          type: string
        - name: tag
          in: body
          description: Updated a policy tag
          required: true
          schema:
            $ref: "#/definitions/NewTag"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UpdateTagResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  # Create, get all Policy category in a site
  /customers/{orgid}/sites/{siteid}/tags:
    x-swagger-router-controller: policy_tag

    # Create a policy tag
    post:
      description: Create a policy tag in a site
      operationId: postTag
      parameters:
        - name: orgid
          in: path
          description: The org ID
          required: true
          type: string
        - name: siteid
          in: path
          description: The site ID
          required: true
          type: string
        - name: tag
          in: body
          description: New Policy Tag Details
          required: true
          schema:
            $ref: "#/definitions/NewTag"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/PostTagResponse"
        "404":
          description: Policy Tag Not Created
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"          
    
    # Get all policy tags
    get:
      description: Get all policy tags in a site
      operationId: getAllTags
      parameters:
        - name: orgid
          in: path
          description: The org ID
          required: true
          type: string
        - name: siteid
          in: path
          description: The site ID
          required: true
          type: string              
      responses:
        "200":
          description: Success
          schema:
            type: array
            items: 
              # a pointer to a definition
              $ref: "#/definitions/GetAllTagsResponse"
        "404":
          description: Policy Categories Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"  

   # Get, Update, Delete  a specific parking policy
  /customers/{orgid}/sites/{siteid}/parkingpolicies/{parkingpolicyid}:
    x-swagger-router-controller: parking_policy
    # Get a parking policy 
    get:
      description: Get a specific parking policy in a site
      operationId: getParkingPolicy
      parameters:
        - name: orgid
          in: path
          description: The org ID
          required: true
          type: string
        - name: siteid
          in: path
          description: The site ID
          required: true
          type: string
        - name: parkingpolicyid
          in: path
          description: The parking policy ID
          required: true
          type: string        
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GetParkingPolicyResponse"
        "404":
          description: Parking Policy Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 

    # Delete a policy category
    delete:
      description: Delete a parking policy in a site
      operationId: deleteParkingPolicy
      parameters:
        - name: orgid
          in: path
          description: The customer ID
          required: true
          type: string
        - name: siteid
          in: path
          description: The site ID
          required: true
          type: string
        - name: parkingpolicyid
          in: path
          description: The parking policy ID
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DeleteParkingPolicyResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 

    # Update a parking policy
    post:
      description: Update a parking policy
      operationId: updateParkingPolicy
      parameters:
        - name: orgid
          in: path
          description: The customer ID
          required: true
          type: string
        - name: siteid
          in: path
          description: The site ID
          required: true
          type: string
        - name: parkingpolicyid
          in: path
          description: The parking policy ID
          required: true
          type: string
        - name: policy
          in: body
          description: Updated a parking policy
          required: true
          schema:
            $ref: "#/definitions/NewParkingPolicy"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UpdateParkingPolicyResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

   # Create, get all parking policy in a site
  /customers/{orgid}/sites/{siteid}/parkingpolicies:
    x-swagger-router-controller: parking_policy

    # Create a parking policy
    post:
      description: Create a parking policy in a site
      operationId: createParkingPolicy
      parameters:
        - name: orgid
          in: path
          description: The org ID
          required: true
          type: string
        - name: siteid
          in: path
          description: The site ID
          required: true
          type: string
        - name: policy
          in: body
          description: New Parking Policy Details
          required: true
          schema:
            $ref: "#/definitions/NewParkingPolicy"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CreateParkingPolicyResponse"
        "404":
          description: Policy Category Not Created
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

    # Get all policy categories
    get:
      description: Get all parking policies in a site
      operationId: getAllParkingPolicy
      parameters:
        - name: orgid
          in: path
          description: The org ID
          required: true
          type: string
        - name: siteid
          in: path
          description: The site ID
          required: true
          type: string              
      responses:
        "200":
          description: Success
          schema:
            type: array
            items: 
              # a pointer to a definition
              $ref: "#/definitions/GetAllParkingPoliciesResponse"
        "404":
          description: Parking Policy Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"  

    # Group-Policy Assocation in a site
  /customers/{orgid}/sites/{siteid}/policyassociation:
    x-swagger-router-controller: group_policy

    # Associate a group-policy
    post:
      description: Associate a group-policy in a site
      operationId: policyassociation
      parameters:
        - name: orgid
          in: path
          description: The org ID
          required: true
          type: string
        - name: siteid
          in: path
          description: The site ID
          required: true
          type: string
        - name: grouppolicy
          in: body
          description: Associating Group Policy Details
          required: true
          schema:
            $ref: "#/definitions/GroupPolicy"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/AssociateGroupPolicyResponse"
        "404":
          description: Group Policy Not Associated
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

     # Group-Policy Deassociation in a site
  /customers/{orgid}/sites/{siteid}/policydisassociation:
    x-swagger-router-controller: group_policy

    # Deassociate a group-policy
    post:
      description: Deassociate a group-policy in a site
      operationId: policydisassociation
      parameters:
        - name: orgid
          in: path
          description: The org ID
          required: true
          type: string
        - name: siteid
          in: path
          description: The site ID
          required: true
          type: string
        - name: grouppolicy
          in: body
          description: Deassociating Group Policy Details
          required: true
          schema:
            $ref: "#/definitions/GroupPolicy"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/DeassociateGroupPolicyResponse"
        "404":
          description: Group Policy Not Deassociated
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw    
  
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
        
  NewTag: 
    type: object
    required:
      - name
    properties:
      name:
        type: string
      description:
        type: string
      uid:
        type: string
        default: 'null'
      orgid:
        type: string
        default: 'null'
      siteid:
        type: string
        default: 'null'
      createdon:
        default: null
      lastupdated:
        default: null
      isdeleted:
        default: null

  NewParkingPolicy: 
    type: object
    required:
      - name
      - policyAuthorizerid
    properties:
      name:
        type: string
      policyAuthorizerid:
        type: string

  GroupPolicy:
    type: object
    required:
      - parkinggroupid
      - policyid
    properties:
      parkinggroupid:
        type: string
      policyid:
        type: string  

  PostTagResponse:
    type: object 

  GetTagResponse:
    type: object    
  
  GetAllTagsResponse:
    type: object
  
  UpdateTagResponse:
    type: object

  DeleteTagResponse:
    type: object

  GetParkingPolicyResponse:
    type: object

  CreateParkingPolicyResponse:
    type: object

  UpdateParkingPolicyResponse:
    type: object

  GetAllParkingPoliciesResponse:
    type: object
  
  DeleteParkingPolicyResponse:
    type: object

  AssociateGroupPolicyResponse:
    type: object

  DeassociateGroupPolicyResponse:
    type: object

  ErrorResponse:
    #required:
    #  - message
    properties:
      message:
        type: string